service:
  name: geo-tool

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  logRetentionInDays: 30
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  nuxt:
    handler: server/index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-offline

custom:
  defaultStage: dev
  environment:
    dev: ${file(./config/development.yml)}
    prod: ${file(./config/production.yml)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.environment.${self:provider.stage}.domain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
