org: qazsato

app: geodig

service: geo-tool

stages:
  prod:
    params: ${file(./config/production.yml)}
  dev:
    params: ${file(./config/development.yml)}

provider:
  # General settings
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  # General AWS Lambda settings
  runtime: nodejs20.x
  memorySize: 1024
  logRetentionInDays: 30
  timeout: 20
  environment:
    TZ: Asia/Tokyo
    NODE_ENV: ${self:provider.stage}
  versionFunctions: false
  architecture: arm64

functions:
  nuxt:
    handler: server/index.nuxt
    url: true

custom:
  defaultStage: dev
