service: geo-tool

frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  logRetentionInDays: 30
  timeout: 20
  versionFunctions: false
  architecture: arm64
  environment:
    TZ: Asia/Tokyo
    NODE_ENV: ${self:provider.stage}

functions:
  nuxt:
    handler: server/index.nuxt
    url: true

custom:
  defaultStage: dev
  environment:
    dev: ${file(./config/development.yml)}
    prod: ${file(./config/production.yml)}
