service: geo-tool

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 512
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  logRetentionInDays: 30
  timeout: 20
  versionFunctions: false
  architecture: arm64
  environment:
    NODE_ENV: ${self:provider.stage}
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  nuxt:
    handler: server/index.nuxt
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

custom:
  defaultStage: dev
  environment:
    dev: ${file(./config/development.yml)}
    prod: ${file(./config/production.yml)}
